remote_theme: vinitkumar/white-paper
title: DeerCMS
description: The official homepage of DeerCMS.

logo: https://avatars.githubusercontent.com/u/147345514?v=4

owner:
  name: Tobias Röder
  avatar: https://avatars.githubusercontent.com/u/24211899?v=4
  github: https://github.com/tobiasroeder

plugins:
  - jekyll-remote-theme
